### ISSUE TITLE
Problem at launch - missing path

### ISSUE THREAD

**Issue by theonaciri** [radiovisual/npm-install-que#2]
Hi,
I installed your module on my Debian like so :
`sudo npm install --global npm-install-que`

Launched like that :
`sudo npm-install-que strongloop -g`

Received this error :
`(node:18668) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError: missing path`

What path should I set to make it work ?

**Comment by radiovisual** [comment]
`npm-install-que` is meant to install your **project** dependencies one at a time, and it always finds your modules from inside your `package.json` file. Basically, this module just takes the place of the `npm install` command *without any parameters*, which means there is no support for global modules.

The reason why this command isn't supported:

```
$ npm-install-que modulename -g
```

...is because with global modules, you can already use npm to install global modules "one at a time" with:

```
$ npm install modulename -g
```

`npm-install-que` is just meant to break up your project dependencies and attempt to install them one at a time, and print out a useful retry string to help you attempt to re-install the packages that failed.

If you want to install only a single global package, then just use `npm install -g modulename`

I will update the readme with a note about how this module doesn't take parameters, so that others won't try to use it as a replacement for `npm install` to install global packages. Thanks for reporting!

Also, as a side note, you should not need to use `sudo` with npm. You can fix your npm permissions by reading this: [https://docs.npmjs.com/getting-started/fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

**Comment by theonaciri** [comment]
Thanks a lot !
