### ISSUE TITLE
install order

### ISSUE THREAD

**Issue by vboius** [radiovisual/npm-install-que#3]
Why does your modules starts from end ?

In this way some modules say "unmet dependencies"  while needed modules are in order to be installed.

**Comment by radiovisual** [comment]
Yeah, I never really put too much consideration into the order of the module installation, the only important thing was to install one-by-one to find any problems with the install process, (and/or isolate problematic modules). 

But you are right, this module does install the modules in the reverse-order as they appear in the package.json file, because I am grabbing the module to install via the [`pop()` method on line 26](https://github.com/radiovisual/npm-install-que/blob/master/que.js#L26). Simply switching that line to read `var p = deps.shift();` might make the modules install in the same order in which they are defined in the package.json, but I don't have time this week to test it out and see if changing that one line might change the logic elsewhere in the module. 

If you want to submit a PR that uses `shift()` and still passes the tests, I will merge it.

Thanks for pointing this out.
